name: "Security: Secrets"

on:
  workflow_dispatch:
  push:
  pull_request:
  #schedule:
  #  - cron:  '0 0 * * 0'

jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: TruffleHog Scan
        uses: edplato/trufflehog-actions-scan@6cf4d6ab0edcfee4251c8c4d214e3655b84c6cb6 # 0.9m-beta
