name: "Security: Secrets"

on:
  workflow_dispatch:
  push:
  pull_request:
  #schedule:
  #  - cron:  '0 0 * * 0'

jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: TruffleHog Scan
        uses: edplato/trufflehog-actions-scan@master