name: "Committed Secrets Check"

on:
  workflow_dispatch:
  push:
  pull_request:
#  schedule:
#    - cron:  '0 0 * * *'

jobs:
  Trufflehog:
    runs-on: ubuntu-latest
    name: Trufflehog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan
        uses: edplato/trufflehog-actions-scan@master